#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ChristmasBirdCountApp.Resource", IsApplication=true)]

namespace ChristmasBirdCountApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int audubon_society = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int audubon_society2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060023
			public const int btnAdd = 2131099683;
			
			// aapt resource value: 0x7f060001
			public const int btnAddBirds = 2131099649;
			
			// aapt resource value: 0x7f060022
			public const int btnClear = 2131099682;
			
			// aapt resource value: 0x7f06002d
			public const int btnClearListing = 2131099693;
			
			// aapt resource value: 0x7f060002
			public const int btnEditBird = 2131099650;
			
			// aapt resource value: 0x7f06001f
			public const int btnReturn = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int btnSend = 2131099680;
			
			// aapt resource value: 0x7f060024
			public const int btnSubmit = 2131099684;
			
			// aapt resource value: 0x7f06002c
			public const int btnUpdateListing = 2131099692;
			
			// aapt resource value: 0x7f060028
			public const int lblBirdName = 2131099688;
			
			// aapt resource value: 0x7f06000d
			public const int lblHoursDriven = 2131099661;
			
			// aapt resource value: 0x7f060019
			public const int lblHoursOwling = 2131099673;
			
			// aapt resource value: 0x7f060013
			public const int lblHoursWalked = 2131099667;
			
			// aapt resource value: 0x7f060010
			public const int lblMilesDriven = 2131099664;
			
			// aapt resource value: 0x7f060016
			public const int lblMilesWalked = 2131099670;
			
			// aapt resource value: 0x7f06001c
			public const int lblNotes = 2131099676;
			
			// aapt resource value: 0x7f060007
			public const int lblPartyMembers = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int lblRecipientEmail = 2131099652;
			
			// aapt resource value: 0x7f06000a
			public const int lblRegion = 2131099658;
			
			// aapt resource value: 0x7f06002e
			public const int left = 2131099694;
			
			// aapt resource value: 0x7f06002a
			public const int linearLayoutBirdCount = 2131099690;
			
			// aapt resource value: 0x7f060027
			public const int linearLayoutBirdName = 2131099687;
			
			// aapt resource value: 0x7f060003
			public const int linearLayoutEmailRecipient = 2131099651;
			
			// aapt resource value: 0x7f06000c
			public const int linearLayoutHoursDriven = 2131099660;
			
			// aapt resource value: 0x7f060018
			public const int linearLayoutHoursOwling = 2131099672;
			
			// aapt resource value: 0x7f060012
			public const int linearLayoutHoursWalked = 2131099666;
			
			// aapt resource value: 0x7f060021
			public const int linearLayoutMainScreen = 2131099681;
			
			// aapt resource value: 0x7f06000f
			public const int linearLayoutMilesDriven = 2131099663;
			
			// aapt resource value: 0x7f060015
			public const int linearLayoutMilesWalked = 2131099669;
			
			// aapt resource value: 0x7f06001e
			public const int linearLayoutNavigateSubmitPage = 2131099678;
			
			// aapt resource value: 0x7f06001b
			public const int linearLayoutNotes = 2131099675;
			
			// aapt resource value: 0x7f060006
			public const int linearLayoutPartyMembers = 2131099654;
			
			// aapt resource value: 0x7f060009
			public const int linearLayoutRegion = 2131099657;
			
			// aapt resource value: 0x7f060026
			public const int myListView = 2131099686;
			
			// aapt resource value: 0x7f06002f
			public const int right = 2131099695;
			
			// aapt resource value: 0x7f06000b
			public const int spnRegion = 2131099659;
			
			// aapt resource value: 0x7f06002b
			public const int txtBirdCount = 2131099691;
			
			// aapt resource value: 0x7f060029
			public const int txtBirdName = 2131099689;
			
			// aapt resource value: 0x7f06000e
			public const int txtHoursDriven = 2131099662;
			
			// aapt resource value: 0x7f06001a
			public const int txtHoursOwling = 2131099674;
			
			// aapt resource value: 0x7f060014
			public const int txtHoursWalked = 2131099668;
			
			// aapt resource value: 0x7f060011
			public const int txtMilesDriven = 2131099665;
			
			// aapt resource value: 0x7f060017
			public const int txtMilesWalked = 2131099671;
			
			// aapt resource value: 0x7f06001d
			public const int txtNotes = 2131099677;
			
			// aapt resource value: 0x7f060000
			public const int txtNumber = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int txtPartyMembers = 2131099656;
			
			// aapt resource value: 0x7f060005
			public const int txtRecipientEmail = 2131099653;
			
			// aapt resource value: 0x7f060025
			public const int txtname = 2131099685;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BulkAdd = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EmailForm = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Pop = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int row = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
