#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ChristmasBirdCountApp.Resource", IsApplication=true)]

namespace ChristmasBirdCountApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050002
			public const int state_array = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int time_optional_array = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int times_array = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int audubon_society = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int audubon_society2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int selector = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int whiteBird = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int WhiteReport = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int whiteTrashCan = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000d
			public const int addBirdListView = 2131165197;
			
			// aapt resource value: 0x7f07000f
			public const int btnAddBirds = 2131165199;
			
			// aapt resource value: 0x7f070018
			public const int btnCancel = 2131165208;
			
			// aapt resource value: 0x7f070016
			public const int btnCancelSubmit = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int btnClearList = 2131165207;
			
			// aapt resource value: 0x7f070093
			public const int btnClearListing = 2131165331;
			
			// aapt resource value: 0x7f070015
			public const int btnCountWeekCount = 2131165205;
			
			// aapt resource value: 0x7f070010
			public const int btnEditBird = 2131165200;
			
			// aapt resource value: 0x7f070014
			public const int btnFeederCount = 2131165204;
			
			// aapt resource value: 0x7f070013
			public const int btnFieldCount = 2131165203;
			
			// aapt resource value: 0x7f07003c
			public const int btnSend = 2131165244;
			
			// aapt resource value: 0x7f070092
			public const int btnUpdateListing = 2131165330;
			
			// aapt resource value: 0x7f07000c
			public const int ibAddBirdClearFilter = 2131165196;
			
			// aapt resource value: 0x7f07002e
			public const int ibCityClearField = 2131165230;
			
			// aapt resource value: 0x7f070001
			public const int ibClear = 2131165185;
			
			// aapt resource value: 0x7f07008e
			public const int ibClearFilter = 2131165326;
			
			// aapt resource value: 0x7f070040
			public const int ibCountCircleClearField = 2131165248;
			
			// aapt resource value: 0x7f070024
			public const int ibCounterEmailClearField = 2131165220;
			
			// aapt resource value: 0x7f07001c
			public const int ibEmailClearField = 2131165212;
			
			// aapt resource value: 0x7f070070
			public const int ibEnd1ClearField = 2131165296;
			
			// aapt resource value: 0x7f070078
			public const int ibEnd2ClearField = 2131165304;
			
			// aapt resource value: 0x7f07007c
			public const int ibHDClearField = 2131165308;
			
			// aapt resource value: 0x7f07008c
			public const int ibHOClearField = 2131165324;
			
			// aapt resource value: 0x7f070084
			public const int ibHWClearField = 2131165316;
			
			// aapt resource value: 0x7f070052
			public const int ibHoursObservingClearField = 2131165266;
			
			// aapt resource value: 0x7f070080
			public const int ibMDClearField = 2131165312;
			
			// aapt resource value: 0x7f070088
			public const int ibMWClearField = 2131165320;
			
			// aapt resource value: 0x7f07003a
			public const int ibNotesClearField = 2131165242;
			
			// aapt resource value: 0x7f07004c
			public const int ibObserverEmailClearField = 2131165260;
			
			// aapt resource value: 0x7f070044
			public const int ibObserverNameClearField = 2131165252;
			
			// aapt resource value: 0x7f070048
			public const int ibObserverPhoneClearField = 2131165256;
			
			// aapt resource value: 0x7f070056
			public const int ibPartyClearField = 2131165270;
			
			// aapt resource value: 0x7f07005a
			public const int ibPartySizeClearField = 2131165274;
			
			// aapt resource value: 0x7f070020
			public const int ibPhoneNumberClearField = 2131165216;
			
			// aapt resource value: 0x7f07006c
			public const int ibStart1ClearField = 2131165292;
			
			// aapt resource value: 0x7f070074
			public const int ibStart2ClearField = 2131165300;
			
			// aapt resource value: 0x7f070032
			public const int ibStateClearField = 2131165234;
			
			// aapt resource value: 0x7f07002a
			public const int ibStreetClearField = 2131165226;
			
			// aapt resource value: 0x7f070066
			public const int ibTeamLeaderEmailClearField = 2131165286;
			
			// aapt resource value: 0x7f07005e
			public const int ibTeamLeaderNameClearField = 2131165278;
			
			// aapt resource value: 0x7f070062
			public const int ibTeamLeaderPhoneClearField = 2131165282;
			
			// aapt resource value: 0x7f070036
			public const int ibZIPCodeClearField = 2131165238;
			
			// aapt resource value: 0x7f070004
			public const int imageView2 = 2131165188;
			
			// aapt resource value: 0x7f070007
			public const int imageView3 = 2131165191;
			
			// aapt resource value: 0x7f070005
			public const int lblAdd = 2131165189;
			
			// aapt resource value: 0x7f070009
			public const int lblAddBirdInstructions = 2131165193;
			
			// aapt resource value: 0x7f070090
			public const int lblBirdName = 2131165328;
			
			// aapt resource value: 0x7f07002c
			public const int lblCity = 2131165228;
			
			// aapt resource value: 0x7f070002
			public const int lblClear = 2131165186;
			
			// aapt resource value: 0x7f07003e
			public const int lblCountCircle = 2131165246;
			
			// aapt resource value: 0x7f070026
			public const int lblCounterAddress = 2131165222;
			
			// aapt resource value: 0x7f070022
			public const int lblCounterEmail = 2131165218;
			
			// aapt resource value: 0x7f07006e
			public const int lblEnd1 = 2131165294;
			
			// aapt resource value: 0x7f070076
			public const int lblEnd2 = 2131165302;
			
			// aapt resource value: 0x7f07004e
			public const int lblFeederAddress = 2131165262;
			
			// aapt resource value: 0x7f07007a
			public const int lblHoursDriven = 2131165306;
			
			// aapt resource value: 0x7f070050
			public const int lblHoursObserving = 2131165264;
			
			// aapt resource value: 0x7f07008a
			public const int lblHoursOwling = 2131165322;
			
			// aapt resource value: 0x7f070082
			public const int lblHoursWalked = 2131165314;
			
			// aapt resource value: 0x7f07007e
			public const int lblMilesDriven = 2131165310;
			
			// aapt resource value: 0x7f070086
			public const int lblMilesWalked = 2131165318;
			
			// aapt resource value: 0x7f070038
			public const int lblNotes = 2131165240;
			
			// aapt resource value: 0x7f070042
			public const int lblObserver = 2131165250;
			
			// aapt resource value: 0x7f07004a
			public const int lblObserverEmail = 2131165258;
			
			// aapt resource value: 0x7f070046
			public const int lblObserverPhone = 2131165254;
			
			// aapt resource value: 0x7f070054
			public const int lblPartyMembers = 2131165268;
			
			// aapt resource value: 0x7f070058
			public const int lblPartySize = 2131165272;
			
			// aapt resource value: 0x7f07001e
			public const int lblPhoneNumber = 2131165214;
			
			// aapt resource value: 0x7f07001a
			public const int lblRecipientEmail = 2131165210;
			
			// aapt resource value: 0x7f07006a
			public const int lblStart1 = 2131165290;
			
			// aapt resource value: 0x7f070072
			public const int lblStart2 = 2131165298;
			
			// aapt resource value: 0x7f070030
			public const int lblState = 2131165232;
			
			// aapt resource value: 0x7f070028
			public const int lblStreet = 2131165224;
			
			// aapt resource value: 0x7f070008
			public const int lblSubmit = 2131165192;
			
			// aapt resource value: 0x7f070068
			public const int lblTeamLeaderAddress = 2131165288;
			
			// aapt resource value: 0x7f070064
			public const int lblTeamLeaderEmail = 2131165284;
			
			// aapt resource value: 0x7f07005c
			public const int lblTeamLeaderName = 2131165276;
			
			// aapt resource value: 0x7f070060
			public const int lblTeamLeaderPhone = 2131165280;
			
			// aapt resource value: 0x7f070011
			public const int lblTitle = 2131165201;
			
			// aapt resource value: 0x7f070034
			public const int lblZIPCode = 2131165236;
			
			// aapt resource value: 0x7f070094
			public const int left = 2131165332;
			
			// aapt resource value: 0x7f07000a
			public const int linearLayoutAddBirdFilter = 2131165194;
			
			// aapt resource value: 0x7f070012
			public const int linearLayoutBirdCount = 2131165202;
			
			// aapt resource value: 0x7f07002b
			public const int linearLayoutCity = 2131165227;
			
			// aapt resource value: 0x7f07003d
			public const int linearLayoutCountCircle = 2131165245;
			
			// aapt resource value: 0x7f070025
			public const int linearLayoutCounterAddress = 2131165221;
			
			// aapt resource value: 0x7f070021
			public const int linearLayoutCounterEmail = 2131165217;
			
			// aapt resource value: 0x7f07001d
			public const int linearLayoutCounterPhone = 2131165213;
			
			// aapt resource value: 0x7f070019
			public const int linearLayoutEmailRecipient = 2131165209;
			
			// aapt resource value: 0x7f07006d
			public const int linearLayoutEnd1 = 2131165293;
			
			// aapt resource value: 0x7f070075
			public const int linearLayoutEnd2 = 2131165301;
			
			// aapt resource value: 0x7f07004d
			public const int linearLayoutFeederAddress = 2131165261;
			
			// aapt resource value: 0x7f070041
			public const int linearLayoutFeederObserver = 2131165249;
			
			// aapt resource value: 0x7f070079
			public const int linearLayoutHoursDriven = 2131165305;
			
			// aapt resource value: 0x7f07004f
			public const int linearLayoutHoursObserving = 2131165263;
			
			// aapt resource value: 0x7f070089
			public const int linearLayoutHoursOwling = 2131165321;
			
			// aapt resource value: 0x7f070081
			public const int linearLayoutHoursWalked = 2131165313;
			
			// aapt resource value: 0x7f07007d
			public const int linearLayoutMilesDriven = 2131165309;
			
			// aapt resource value: 0x7f070085
			public const int linearLayoutMilesWalked = 2131165317;
			
			// aapt resource value: 0x7f07003b
			public const int linearLayoutNavigateSubmitPage = 2131165243;
			
			// aapt resource value: 0x7f070037
			public const int linearLayoutNotes = 2131165239;
			
			// aapt resource value: 0x7f070049
			public const int linearLayoutObserverEmail = 2131165257;
			
			// aapt resource value: 0x7f070045
			public const int linearLayoutObserverPhone = 2131165253;
			
			// aapt resource value: 0x7f070053
			public const int linearLayoutPartyMembers = 2131165267;
			
			// aapt resource value: 0x7f070057
			public const int linearLayoutPartySize = 2131165271;
			
			// aapt resource value: 0x7f070069
			public const int linearLayoutStart1 = 2131165289;
			
			// aapt resource value: 0x7f070071
			public const int linearLayoutStartEnd2 = 2131165297;
			
			// aapt resource value: 0x7f07002f
			public const int linearLayoutState = 2131165231;
			
			// aapt resource value: 0x7f070027
			public const int linearLayoutStreet = 2131165223;
			
			// aapt resource value: 0x7f070067
			public const int linearLayoutTeamLeadAddress = 2131165287;
			
			// aapt resource value: 0x7f070063
			public const int linearLayoutTeamLeaderEmail = 2131165283;
			
			// aapt resource value: 0x7f07005b
			public const int linearLayoutTeamLeaderName = 2131165275;
			
			// aapt resource value: 0x7f07005f
			public const int linearLayoutTeamLeaderPhone = 2131165279;
			
			// aapt resource value: 0x7f070033
			public const int linearLayoutZIPCode = 2131165235;
			
			// aapt resource value: 0x7f070003
			public const int llAdd = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int llClear = 2131165184;
			
			// aapt resource value: 0x7f070006
			public const int llSubmit = 2131165190;
			
			// aapt resource value: 0x7f07008f
			public const int myListView = 2131165327;
			
			// aapt resource value: 0x7f070095
			public const int right = 2131165333;
			
			// aapt resource value: 0x7f07006f
			public const int spinnerEndTime1 = 2131165295;
			
			// aapt resource value: 0x7f070077
			public const int spinnerEndTime2 = 2131165303;
			
			// aapt resource value: 0x7f07006b
			public const int spinnerStartTime1 = 2131165291;
			
			// aapt resource value: 0x7f070073
			public const int spinnerStartTime2 = 2131165299;
			
			// aapt resource value: 0x7f070031
			public const int spinnerState = 2131165233;
			
			// aapt resource value: 0x7f07000b
			public const int txtAddBirdNameFilter = 2131165195;
			
			// aapt resource value: 0x7f070091
			public const int txtBirdCount = 2131165329;
			
			// aapt resource value: 0x7f07002d
			public const int txtCity = 2131165229;
			
			// aapt resource value: 0x7f07003f
			public const int txtCountCircle = 2131165247;
			
			// aapt resource value: 0x7f070023
			public const int txtCounterEmail = 2131165219;
			
			// aapt resource value: 0x7f07007b
			public const int txtHoursDriven = 2131165307;
			
			// aapt resource value: 0x7f070051
			public const int txtHoursObserving = 2131165265;
			
			// aapt resource value: 0x7f07008b
			public const int txtHoursOwling = 2131165323;
			
			// aapt resource value: 0x7f070083
			public const int txtHoursWalked = 2131165315;
			
			// aapt resource value: 0x7f07007f
			public const int txtMilesDriven = 2131165311;
			
			// aapt resource value: 0x7f070087
			public const int txtMilesWalked = 2131165319;
			
			// aapt resource value: 0x7f07008d
			public const int txtNameFilter = 2131165325;
			
			// aapt resource value: 0x7f070039
			public const int txtNotes = 2131165241;
			
			// aapt resource value: 0x7f07000e
			public const int txtNumber = 2131165198;
			
			// aapt resource value: 0x7f07004b
			public const int txtObserverEmail = 2131165259;
			
			// aapt resource value: 0x7f070043
			public const int txtObserverName = 2131165251;
			
			// aapt resource value: 0x7f070047
			public const int txtObserverPhone = 2131165255;
			
			// aapt resource value: 0x7f070055
			public const int txtPartyMembers = 2131165269;
			
			// aapt resource value: 0x7f070059
			public const int txtPartySize = 2131165273;
			
			// aapt resource value: 0x7f07001f
			public const int txtPhoneNumber = 2131165215;
			
			// aapt resource value: 0x7f07001b
			public const int txtRecipientEmail = 2131165211;
			
			// aapt resource value: 0x7f070029
			public const int txtStreet = 2131165225;
			
			// aapt resource value: 0x7f070065
			public const int txtTeamLeaderEmail = 2131165285;
			
			// aapt resource value: 0x7f07005d
			public const int txtTeamLeaderName = 2131165277;
			
			// aapt resource value: 0x7f070061
			public const int txtTeamLeaderPhone = 2131165281;
			
			// aapt resource value: 0x7f070035
			public const int txtZIPCode = 2131165237;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int actionBar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AddBirdPopUp = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int BulkAdd = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ChooseCountTypePopUp = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ClearAllPopUp = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int CountWeekEmailForm = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int FeederEmailForm = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int FieldEmailForm = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Main = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Pop = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int row = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int ClearFieldIconDescription = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int ClearFilterIconDescription = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int state_selection = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int time_selection = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int CustomActionBarTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int MyActionBar = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
